CREATE DATABASE IF NOT EXISTS quiz;
USE quiz;

CREATE TABLE guestbook (
    id INT AUTO_INCREMENT PRIMARY KEY,
    visitor_name VARCHAR(100) NOT NULL,
    message TEXT NOT NULL,
    posted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);